language: ruby

sudo: required

services:
  - docker

before_install:
  - docker build . -t cyberninjas/puppet-modules

script:
  - docker run -v $(pwd):/usr/src/puppet-modules cyberninjas/puppet-modules
